# Numpy <hr style="border:2.5px solid #a8f9ffff"></hr>

<b>Kianlee Paul D. Rosales</b>
<br>Computer Engineer

In [2]:
# imports and packages
import numpy as np

# 1D Array

In [3]:
my_array = [1, 2, 3]

In [6]:
type(my_array)

numpy.ndarray

In [5]:
my_array = np.array([1, 2, 3])

In [7]:
np.shape(my_array)

(3,)

# 2D Array

In [26]:
my_array = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
my_array

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
np.shape(my_array)

(2, 3)

In [28]:
trans_array = my_array.T

In [29]:
trans_array

array([[1, 4],
       [2, 5],
       [3, 6]])

In [30]:
np.shape(trans_array)

(3, 2)

In [32]:
np.sum(trans_array, axis = 0)

array([ 6, 15])

In [33]:
np.sum(trans_array, axis = 1)

array([5, 7, 9])

# Measure of Central Tendency

In [36]:
resistance = np.array([
    [10.6, 9.1, 9.3, 9.8, 10.5, 10.4, 9.5, 11, 10.4, 3, 9.8], # Jaguar
    [10.1, 11, 9.1, 20, 9.2, 10.8, 9.9, 9.2, 9.1, 9.1, np.nan]  # Panther
])
resistance

array([[10.6,  9.1,  9.3,  9.8, 10.5, 10.4,  9.5, 11. , 10.4,  3. ,  9.8],
       [10.1, 11. ,  9.1, 20. ,  9.2, 10.8,  9.9,  9.2,  9.1,  9.1,  nan]])

In [39]:
#Mean
np.nanmean(resistance, axis = 1)

array([ 9.4 , 10.75])